### ISSUE TITLE
Indigo upgrade meta-issue

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#139]
This is just a draft of the main changes we're thinking of putting in for indigo
- [x] linux_hardware -> ros-drivers/linux_peripheral_interfaces
- [x] turtlebot_msgs/LaptopChargeStatus.msg -> ros-drivers/smart_battery_msgs/SmartBatteryStatus.msg (or similar)
- [x] Upgrade android pairing via rocon interactions
  - no more dual master
  - no android specifications in rapps
  - parameterisable and remappable pairings
  - upgraded android apps
- [x] Support concert mode
- [x] Introduce the rqt remocon/rocon interactions as a standard way of interacting with the turtlebot
- [x] Documentation

Comments welcome.

**Comment by stonier** [comment]
**Deb Conflict - libopenni-sensor-primesense0**

Details of the issue are [here](https://github.com/ros/rosdistro/issues/3986). To resolve it for now:

```
> sudo dpkg --remove --force-remove-reinstreq libopenni-sensor-pointclouds0
> sudo apt-get install -f
```

**Comment by ruffsl** [comment]
Thanks, This worked for me.

**Comment by nlyubova** [comment]
thanks! perfect! it works

**Comment by stonier** [comment]
Closing this, continuing in #170.
